[dev]
  command = "craco start"
  publish = "dist"
  functions = "netlify/functions"
  
[build]
  command = "CI=false craco build"
  functions = "netlify/functions"
  publish = "build/"

[[headers]]
  for = "service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"