[dev]
  command = "craco start"
  port = 3000
  publish = "dist"

[build]
  command = "CI=false craco build && yarn append-sw"
  publish = "build/"

[[headers]]
  for = "service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"