enum Synth {
  KEYS
  JARZO
  DUO
  BLIP
  CELLO
  SUB_BASS
  JARZO2
  PIANO
}

type Shape @embedded {
  points: [Float!]
  colorIndex: Int!
  volume: Int!
  isMuted: Boolean
  quantizeFactor: Float
}

type Project {
  name: String!
  tempo: Int!
  tonic: String!
  scale: String!
  isGridActive: Boolean!
  isSnapToGridActive: Boolean!
  isAutoQuantizeActive: Boolean!
  shapesList: [Shape!]
  userId: String!
  userName: String!
  selectedSynths: [Synth!]
  dateCreated: Long
  knobVals: [[Float!]]
}

type Query {
  allProjects: [Project!]
  projectsByUserId(userId: String!): [Project!]
  allProjectsSortedByDateCreated: [Project!]!
    @resolver(name: "all_projects_sorted_by_title", paginated: true)
}
