type Shape @embedded {
  points: [Float!]
  colorIndex: Int!
  volume: Int!
  isMuted: Boolean
}

type Project {
  name: String!
  tempo: Int!
  tonic: String!
  scale: String!
  isGridActive: Boolean!
  isSnapToGridActive: Boolean!
  isAutoQuantizeActive: Boolean!
  shapesList: [Shape!]
  userId: String!
  userName: String!
}

type Query {
  allProjects: [Project!]
  # ProjectsByCompletedFlag(completed: Boolean!): [Project!]
}
